#!/bin/bash
set -eux

env | sort
pwd

# jupyter-offlinenotebook is automatically installed by repo2docker.
# Uninstall to avoid conflicts
jupyter labextension uninstall --no-build jupyter-offlinenotebook
